export  enum ReviewType {
    REVIEW_TYPE_BASIC_PAYMENT = 1,//'付款审批',
    REVIEW_TYPE_BASIC_TRANSLATE_ADJUST =2, //'转资单审批',
    REVIEW_TYPE_BASIC_TRANSLATE_VOUCHER=3,//'转资单审批',
    BASICACCEPTANCE_APPLY=4,//'验收申请审批',
    REVIEW_TYPE_CONTRACT_MAIN=5//'合同单据审批'
}